"""initial schema

Revision ID: 843870b795d8
Revises: 
Create Date: 2026-06-24 10:11:52.189365+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '843870b795d8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=512), nullable=True),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.Column('added_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_telegram_id'), 'admins', ['telegram_id'], unique=True)
    op.create_table('bot_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('business_connections',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('business_connection_id', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('connected_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('disconnected_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_connections_business_connection_id'), 'business_connections', ['business_connection_id'], unique=True)
    op.create_index(op.f('ix_business_connections_user_id'), 'business_connections', ['user_id'], unique=False)
    op.create_table('media_cache',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('file_unique_id', sa.String(length=255), nullable=False),
    sa.Column('file_id', sa.String(length=512), nullable=False),
    sa.Column('file_type', sa.String(length=30), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('local_path', sa.Text(), nullable=True),
    sa.Column('cached_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_cache_file_unique_id'), 'media_cache', ['file_unique_id'], unique=True)
    op.create_table('messages_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('business_connection_id', sa.String(length=255), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_title', sa.String(length=512), nullable=True),
    sa.Column('sender_id', sa.BigInteger(), nullable=True),
    sa.Column('sender_name', sa.String(length=512), nullable=True),
    sa.Column('sender_username', sa.String(length=255), nullable=True),
    sa.Column('is_outgoing', sa.Boolean(), nullable=False),
    sa.Column('message_type', sa.String(length=30), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('file_id', sa.String(length=512), nullable=True),
    sa.Column('file_unique_id', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('local_path', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('edit_count', sa.Integer(), nullable=False),
    sa.Column('received_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('edited_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_file_unique', 'messages_log', ['file_unique_id'], unique=False)
    op.create_index('ix_messages_lookup', 'messages_log', ['user_id', 'chat_id', 'message_id'], unique=False)
    op.create_index('ix_messages_received', 'messages_log', ['received_at'], unique=False)
    op.create_index('ix_messages_user_chat', 'messages_log', ['user_id', 'chat_id'], unique=False)
    op.create_index('ix_messages_user_deleted', 'messages_log', ['user_id', 'is_deleted'], unique=False)
    op.create_table('promo_codes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('duration_label', sa.String(length=50), nullable=True),
    sa.Column('used_by', sa.BigInteger(), nullable=True),
    sa.Column('used_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('code_expires_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('access_expires_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promo_codes_code'), 'promo_codes', ['code'], unique=True)
    op.create_table('subscriptions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('tariff_id', sa.BigInteger(), nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('promo_code_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_payment_charge_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('tariffs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('price_stars', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=512), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('subscription_status', sa.String(length=20), nullable=False),
    sa.Column('subscription_expires_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('ban_reason', sa.Text(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_active_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('tariffs')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_promo_codes_code'), table_name='promo_codes')
    op.drop_table('promo_codes')
    op.drop_index('ix_messages_user_deleted', table_name='messages_log')
    op.drop_index('ix_messages_user_chat', table_name='messages_log')
    op.drop_index('ix_messages_received', table_name='messages_log')
    op.drop_index('ix_messages_lookup', table_name='messages_log')
    op.drop_index('ix_messages_file_unique', table_name='messages_log')
    op.drop_table('messages_log')
    op.drop_index(op.f('ix_media_cache_file_unique_id'), table_name='media_cache')
    op.drop_table('media_cache')
    op.drop_index(op.f('ix_business_connections_user_id'), table_name='business_connections')
    op.drop_index(op.f('ix_business_connections_business_connection_id'), table_name='business_connections')
    op.drop_table('business_connections')
    op.drop_table('bot_settings')
    op.drop_index(op.f('ix_admins_telegram_id'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
